services:
  payload:
#    image: node:18-alpine
    build: .
    ports:
      - '3000:3000'
    volumes:
#      - .:/home/node/app
      - node_modules:/app/node_modules
      - public:/app/public/media
#    working_dir: /home/node/app/
#    command: sh -c "yarn install && yarn dev"
#    command: sleep 10000s
#    depends_on:
#      - postgresql
    env_file:
      - .env

#  postgresql:
#    image: postgres:17
#    ports:
#      - '5432:5432'
#    shm_size: 128mb
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  pgdata:
  node_modules:
  public:
