services:
  payload:
    build:
      context: .
      args:
        DATABASE_URI: ${DATABASE_URI}
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
        CRON_SECRET: ${CRON_SECRET}
        PREVIEW_SECRET: ${PREVIEW_SECRET}
    volumes:
      - node_modules:/app/node_modules
      - public:/app/public/media
    env_file:
      - .env

volumes:
  node_modules:
  public:
