services:
  payload:
    build:
      context: .
      args:
        DATABASE_URI: ${DATABASE_URI}
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
        COOLIFY_URL: ${COOLIFY_URL}
        CRON_SECRET: ${CRON_SECRET}
        PREVIEW_SECRET: ${PREVIEW_SECRET}
    volumes:
      - node_modules:/app/node_modules
      - public:/app/public/media
      - pdfs:/home/node/app/public/pdfs
    env_file:
      - .env

volumes:
  node_modules:
  public:
  pdfs:
